package edu.augie.finalProgram.taye.Rental;

import edu.augie.finalProgram.taye.Client.Client;
import edu.augie.finalProgram.taye.Vehicle.Vehicle;
import edu.augie.finalProgram.taye.Staff.Employee;
import java.time.LocalDateTime;
import java.util.Iterator;
import java.util.Spliterator;
import java.util.function.Consumer;

public class Rental implements Iterable {

    // attributes of a edu.augie.finalProgram.taye.Rental
    private static int rentalID = 0; // static so it is not reset when an object is made
    private Vehicle vehicle;
    private Client customer;
    private Employee employee;
    private final LocalDateTime startDate;
    private final LocalDateTime endDate;
    private double rate;
    private boolean rentalActive;

    // constructor
    public Rental(Vehicle vehicle, Client customer, Employee employee,
                  LocalDateTime startDate, LocalDateTime endDate, double rate){
        rentalID ++; // increment the id
        this.vehicle = vehicle;
        this.customer = customer;
        this.employee = employee;
        this.startDate = startDate;
        this.endDate = endDate;
        this.rate = rate;

        rentalActive = true;
    }

    // getter and setter methods for all the variables
    public int getRentalID() {
        return rentalID;
    }

    public Vehicle getVehicle() {
        return vehicle;
    }

    public Client getCustomer() {
        return customer;
    }

    public Employee getEmployee() {
        return employee;
    }

    public LocalDateTime getStartDate() {
        return startDate;
    }

    public LocalDateTime getEndDate() {
        return endDate;
    }

    public double getRate() {
        return rate;
    }

    public void setRate(double rate) {
        this.rate = rate;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public void setCustomer(Client customer) {
        this.customer = customer;
    }

    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    // methods to calculate cost
    public double calculateRentalCost(){
        return (endDate.getDayOfYear() - endDate.getDayOfYear()) * rate;
    }

    public void endRental(){
        this.rentalActive = false;
    }

    // custom toString() for Rental object
    @Override
    public String toString() {
        return String.format(
                "+----------------------------------------\n" +
                "|----------------------------------------\n" +
                "|Rental ID:      %d\n" +
                "|VIN:            %d\n" +
                "|Vehicle:        %s\n" +
                "|Year:           %d\n" +
                "|Customer ID:    %d\n" +
                "|Employee ID:    %d\n" +
                "|Rate:           %.2f\n" +
                "|Start Date:     %s\n" +
                "|End Date:       %s\n" +
                "|Duration:       %d\n" +
                "+----------------------------------------\n",
                rentalID,
                vehicle.getVIN(),
                vehicle.getManufacturer() + " " + vehicle.getModel(),
                2025,
                customer.getClientID(),
                employee.getStaffID(),
                rate,
                startDate.toString(),
                endDate.toString(),
                endDate.getDayOfYear() - startDate.getDayOfYear()
        );
    }


    // this was generated by intellij ultimate
    // my iterator in edu.augie.finalProgram.taye.Rental manager wouldn't run without it
    @Override
    public Iterator iterator() {
        return null;
    }

    @Override
    public void forEach(Consumer action) {
        Iterable.super.forEach(action);
    }

    @Override
    public Spliterator spliterator() {
        return Iterable.super.spliterator();
    }
}
